[package]
name = "bit_array"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"

[[bench]]
name = "bit_array"
harness = false

[features]
default = ["std"]
std = []